#!/usr/bin/env bash
#This project displays to infinity and beyond with a sleep
#between each iteration
signal_handler()
{
	echo 'I am invincible'
}
trap signal_handler SIGTERM
while true;
do
	echo "To infinity and beyond"
	sleep 2
done
